### ISSUE TITLE
Escaping invalid characters

### ISSUE THREAD

**Issue by namlook** [assistunion/xml-stream#28]
I have an issue while parsing an XML file:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: not well-formed (invalid token) in line 52584
    at parseChunk (/home/namlook/Documents/Projects/kalitmo/node_modules/xml-stream/lib/xml-stream.js:507:26)
    at ReadStream.<anonymous> (/home/namlook/Documents/Projects/kalitmo/node_modules/xml-stream/lib/xml-stream.js:514:7)
    at ReadStream.EventEmitter.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:746:14)
    at ReadStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ReadStream.Readable.push (_stream_readable.js:127:10)
    at onread (fs.js:1561:12)
```

at the line 52584, I have the character "\x1d". I didn't found a way to make xml-stream ignore this character and continue parsing...

Xml-Stream is a great piece of software but for now I'm stuck with this issue. Any ideas ?

**Comment by aseempatni** [comment]
Any solution to this yet?
