### ISSUE TITLE
Installation failed on OpenSuse 13.2 on iconv@2.1.9

### ISSUE THREAD

**Issue by JavaScriptDude** [assistunion/xml-stream#50]
Installation is failing with  the message:
```
npm ERR! iconv@2.1.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
```

My system is OpenSuse 13.2 and node v0.12.0. Also failed on io.js.

**Comment by klokoy** [comment]
This is also the case on Ubuntu 14.10

**Comment by brndn4** [comment]
Same on CentOS 7.0.1406
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/brandon/node_sandbox/node_modules/xml-stream/node_modules/iconv
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
make: Leaving directory `/home/brandon/node_sandbox/node_modules/xml-stream/node_modules/node-expat/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.10.0-123.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/brandon/node_sandbox/node_modules/xml-stream/node_modules/node-expat
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by brndn4** [comment]
Installing node 0.12 instead of 0.10 fixed this for me.

**Comment by JavaScriptDude** [comment]
Signing out of this one. I switched over to using [sax-js by isaacs] (https://github.com/isaacs/sax-js) which supports streams just fine and does not require gyp.
